/**
 * Hub Common
 *
 * Copyright (C) 2017 Black Duck Software, Inc.
 * http://www.blackducksoftware.com/
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blackducksoftware.integration.hub.api.view;

import java.util.Date;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import com.google.gson.annotations.SerializedName;

/**
 * ActivityDataView
 */
public class ActivityDataView {
    @SerializedName("commitCount12Month")
    private Long commitCount12Month = null;

    @SerializedName("contributorCount12Month")
    private Long contributorCount12Month = null;

    @SerializedName("lastCommitDate")
    private Date lastCommitDate = null;

    /**
     * The overall characteristics of development activity
     */
    public enum TrendingEnum {
        @SerializedName("DECREASING")
        DECREASING("DECREASING"),

        @SerializedName("STABLE")
        STABLE("STABLE"),

        @SerializedName("INCREASING")
        INCREASING("INCREASING");

        private final String value;

        TrendingEnum(final String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }

    @SerializedName("trending")
    private TrendingEnum trending = null;

    public ActivityDataView commitCount12Month(final Long commitCount12Month) {
        this.commitCount12Month = commitCount12Month;
        return this;
    }

    /**
     * The number of commits in a 12 month period
     * 
     * @return commitCount12Month
     **/
    public Long getCommitCount12Month() {
        return commitCount12Month;
    }

    public void setCommitCount12Month(final Long commitCount12Month) {
        this.commitCount12Month = commitCount12Month;
    }

    public ActivityDataView contributorCount12Month(final Long contributorCount12Month) {
        this.contributorCount12Month = contributorCount12Month;
        return this;
    }

    /**
     * The number of contributors in a 12 month period
     * 
     * @return contributorCount12Month
     **/
    public Long getContributorCount12Month() {
        return contributorCount12Month;
    }

    public void setContributorCount12Month(final Long contributorCount12Month) {
        this.contributorCount12Month = contributorCount12Month;
    }

    public ActivityDataView lastCommitDate(final Date lastCommitDate) {
        this.lastCommitDate = lastCommitDate;
        return this;
    }

    /**
     * The last time a commit was made to the project
     * 
     * @return lastCommitDate
     **/
    public Date getLastCommitDate() {
        return lastCommitDate;
    }

    public void setLastCommitDate(final Date lastCommitDate) {
        this.lastCommitDate = lastCommitDate;
    }

    public ActivityDataView trending(final TrendingEnum trending) {
        this.trending = trending;
        return this;
    }

    /**
     * The overall characteristics of development activity
     * 
     * @return trending
     **/
    public TrendingEnum getTrending() {
        return trending;
    }

    public void setTrending(final TrendingEnum trending) {
        this.trending = trending;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this, ToStringStyle.JSON_STYLE);
    }

}
