/**
 * Hub Common
 *
 * Copyright (C) 2017 Black Duck Software, Inc.
 * http://www.blackducksoftware.com/
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blackducksoftware.integration.hub.api.view;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import com.blackducksoftware.integration.hub.model.type.ComplexLicenseEnum;
import com.google.gson.annotations.SerializedName;

/**
 * VersionBomLicenseView
 */
public class VersionBomLicenseView {
    @SerializedName("license")
    private String license = null;

    @SerializedName("licenseDisplay")
    private String licenseDisplay = null;

    @SerializedName("licenseType")
    private ComplexLicenseEnum licenseType = null;

    @SerializedName("licenses")
    private List<VersionBomLicenseView> licenses = new ArrayList<>();

    public VersionBomLicenseView license(final String license) {
        this.license = license;
        return this;
    }

    /**
     * Reference to the full representation of the license
     *
     * @return license
     **/
    public String getLicense() {
        return license;
    }

    public void setLicense(final String license) {
        this.license = license;
    }

    public VersionBomLicenseView licenseDisplay(final String licenseDisplay) {
        this.licenseDisplay = licenseDisplay;
        return this;
    }

    /**
     * Label distinguishing the license from other licenses
     *
     * @return licenseDisplay
     **/
    public String getLicenseDisplay() {
        return licenseDisplay;
    }

    public void setLicenseDisplay(final String licenseDisplay) {
        this.licenseDisplay = licenseDisplay;
    }

    public VersionBomLicenseView licenseType(final ComplexLicenseEnum licenseType) {
        this.licenseType = licenseType;
        return this;
    }

    /**
     * How this license is related to other licenses within a given context
     *
     * @return licenseType
     **/
    public ComplexLicenseEnum getLicenseType() {
        return licenseType;
    }

    public void setLicenseType(final ComplexLicenseEnum licenseType) {
        this.licenseType = licenseType;
    }

    public VersionBomLicenseView licenses(final List<VersionBomLicenseView> licenses) {
        this.licenses = licenses;
        return this;
    }

    public VersionBomLicenseView addLicensesItem(final VersionBomLicenseView licensesItem) {
        this.licenses.add(licensesItem);
        return this;
    }

    /**
     * Additional licenses related to this license via the provided type
     *
     * @return licenses
     **/
    public List<VersionBomLicenseView> getLicenses() {
        return licenses;
    }

    public void setLicenses(final List<VersionBomLicenseView> licenses) {
        this.licenses = licenses;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this, ToStringStyle.JSON_STYLE);
    }

}
